import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Layout from "./components/Layout";
import {ReduxProvider} from "@/app/redux/provider";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <ReduxProvider>
            <Layout>{children}</Layout>
        </ReduxProvider>
      </body>
    </html>
  );
}
