import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import DesktopSidebar from "./components/Layout/DesktopSidebar";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <DesktopSidebar />
        <main>{children}</main>
      </body>
    </html>
  );
}
